config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'contacts#index'
  resources :contacts
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :contact
  STATES = [
          { :key => 'AL', :value => 'Alabama' },
          { :key => 'AK', :value => 'Alaska' },
          { :key => 'AZ', :value => 'Arizona' },
          { :key => 'AR', :value => 'Arkansas' },
          { :key => 'CA', :value => 'California' },
          { :key => 'CO', :value => 'Colorado' },
          { :key => 'CT', :value => 'Connecticut' },
          { :key => 'DE', :value => 'Delaware' },
          { :key => 'DC', :value => 'District of Columbia' },
          { :key => 'FL', :value => 'Florida' },
          { :key => 'GA', :value => 'Georgia' },
          { :key => 'HI', :value => 'Hawaii' },
          { :key => 'ID', :value => 'Idaho' },
          { :key => 'IL', :value => 'Illinois' },
          { :key => 'IN', :value => 'Indiana' },
          { :key => 'IA', :value => 'Iowa' },
          { :key => 'KS', :value => 'Kansas' },
          { :key => 'KY', :value => 'Kentucky' },
          { :key => 'LA', :value => 'Louisiana' },
          { :key => 'ME', :value => 'Maine' },
          { :key => 'MD', :value => 'Maryland' },
          { :key => 'MA', :value => 'Massachusetts' },
          { :key => 'MI', :value => 'Michigan' },
          { :key => 'MN', :value => 'Minnesota' },
          { :key => 'MS', :value => 'Mississippi' },
          { :key => 'MO', :value => 'Missouri' },
          { :key => 'MT', :value => 'Montana' },
          { :key => 'NE', :value => 'Nebraska' },
          { :key => 'NV', :value => 'Nevada' },
          { :key => 'NH', :value => 'New Hampshire' },
          { :key => 'NJ', :value => 'New Jersey' },
          { :key => 'NM', :value => 'New Mexico' },
          { :key => 'NY', :value => 'New York' },
          { :key => 'NC', :value => 'North Carolina' },
          { :key => 'ND', :value => 'North Dakota' },
          { :key => 'OH', :value => 'Ohio' },
          { :key => 'OK', :value => 'Oklahoma' },
          { :key => 'OR', :value => 'Oregon' },
          { :key => 'PA', :value => 'Pennsylvania' },
          { :key => 'RI', :value => 'Rhode Island' },
          { :key => 'SC', :value => 'South Carolina' },
          { :key => 'SD', :value => 'South Dakota' },
          { :key => 'TN', :value => 'Tennessee' },
          { :key => 'TX', :value => 'Texas' },
          { :key => 'UT', :value => 'Utah' },
          { :key => 'VT', :value => 'Vermont' },
          { :key => 'VA', :value => 'Virginia' },
          { :key => 'WA', :value => 'Washington' },
          { :key => 'WV', :value => 'West Virginia' },
          { :key => 'WI', :value => 'Wisconsin' },
          { :key => 'WY', :value => 'Wyoming' },
      ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :addresses
  accepts_nested_attributes_for :addresses, allow_destroy: true
  belongs_to :user

  def full_name
    return "#{first_name} #{last_name}" if last_name || first_name
    
  end

  def address
    
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contacts

  def full_name
    return "#{last_name}, #{first_name}" if last_name || first_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update ]
  before_action :authenticate_user!, except: %i[ index ]
  
  def index
    @contacts = Contact.where(user_id: current_user)
  end

  def show
    
  end

  def new
    @contact = Contact.new
    1.times { @contact.addresses.build }
  end

  def edit

  end

  def update
    
  end

  def create
    @contact = Contact.new(contact_params)
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact = current_user.contacts.where(id: params[:id]).first
    @contact.destroy
    flash[:notice] = "Contact deleted"
    redirect_to root_path
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :number, 
                                    :email, :birthday, :user_id, 
                                    addresses_attributes: 
                                    [:id, :address1, :address2, 
                                    :city, :state, :zip, :_destroy])
  end   

  def set_contact
    @contact = Contact.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/contacts/_contact.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="card shadow-lg" style="width: 30rem; height: 13rem;">
    <%= image_tag("four.jpg", class: "card-img contact-back") %>
      <div class="card-img-overlay">
        <div class="card-body text-white">
          <h5 class="card-title text-center"><%= @contact.full_name %></h5>
          <h6 class="card-subtitle mb-2 font-weight-normal">Phone number: <%= @contact.number%></h6>
          <h6 class="card-subtitle mb-2 font-weight-normal">Birthday: <%= @contact.birthday%></h6>
          <h6 class="card-subtitle mb-2 font-weight-normal">Email: <%= @contact.email%></h6>
          <h6 class="card-subtitle mb-2 font-weight-normal">Address: <% @contact.addresses.each do |address| %>
                                                                    <%= address.address1 %>
                                                                    <%= address.address2 %>,
                                                                    <%= address.city %>,
                                                                    <%= address.state %>
                                                                    <%= address.zip %> 
                                                                    <% end %></h6>
          <%= link_to 'Edit', edit_contact_path, class: "card-link text-warning" %>
          <%= link_to 'Delete', contact_path, class: "card-link text-danger", method: :delete, 
                                              data: {confirm: "Do you wish to delete #{@contact.full_name}?"} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/_form.html.erb
<%= form_with model: @contact do|f| %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputfirstname4">First name</label>
      <%= f.text_field :first_name, autofocus: true, autocomplete: 'first_name', class: 'form-control', placeholder: "First name" %>
    </div>
    <div class="form-group col-md-6">
      <label for="inputlastname4">Last name</label>
      <%= f.text_field :last_name, autocomplete: 'last_name', class: 'form-control', placeholder: "Last name" %>
    </div>

    <div class="form-group col-md-6">
      <label for="inputnumber4">Phone Number</label>
      <%= f.text_field :number, :maxlength => 12, 
                                        autocomplete: 'phone_number', 
                                        class: "form-control", 
                                        placeholder: "xxx-xxx-xxxx" %>
    </div>
    <div class="form-group col-md-6">
      <label for="inputlastname4">Birthday</label>
      <%= f.date_field :birthday, class: 'form-control', placeholder: "MM/DD/YYYY" %>
    </div>

    <div class="form-group col-md-12">
      <label for="inputEmail4">Email</label>
      <%= f.email_field :email, autocomplete: 'email', class: 'form-control', placeholder: "user@example.com" %>
    </div>
  </div>
  <%= f.fields_for :addresses do |af| %>
    <div id="hidden-address">
      <div class="form-group">
        <label for="inputAddress1">Address</label>
        <%= af.text_field :address1, autocomplete: 'address', class: 'form-control', placeholder: "1221 Your St" %>
      </div>
      <div class="form-group">
        <label for="inputAddress2">Address 2</label>
        <%= af.text_field :address2, class: 'form-control', placeholder: "Apt, Studio, or Floor" %>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCity">City</label>
          <%= af.text_field :city, class: 'form-control', placeholder: "City Name" %>
        </div>
        <div class="form-group col-md-4">
          <label for="inputState">State</label>
          <%= af.select :state,  Address::STATES.collect {|s| [ s[:value], s[:key] ] },
                                                          { include_blank: true }, 
                                                          {class: 'form-control', required: true} %>
        </div>
        <div class="form-group col-md-2">
          <label for="inputZip">Zip</label>
          <%= af.text_field :zip, :maxlength => 5, class: "form-control", placeholder: "12345" %>
        </div>
      </div>
      <script type="text/javascript">
      $(document).ready(function(){
      window.alert("test");
      })
      </script>
    </div>
    <button type="button" id="clone_btn" class="btn btn-primary">Clone</button>
  <% end %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.submit 'Create Contact', class: "btn btn-secondary" %>
<% end %>

app/views/contacts/edit.html.erb
<div class="container contact-area">
  <div class="justify-content-center">
    <%= render 'form' %>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="container header-index">
  <div class="jumbotron text-center text-white shadow-sm">
    <div class="container header-space">
      <h1 class="display-3 contact-head">4 Your Contacts</h1>
      <hr class="my-1">
      <% if user_signed_in? %>
      <%= link_to 'New Contact', new_contact_path, class: "btn btn-outline-secondary btn-sm" %>
      <% else %>
      <%= link_to 'Login', new_user_session_path, class: "btn btn-outline-secondary btn-sm" %>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <table class="table table-hover shadow-sm">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Last Name:</th>
        <th scope="col">First Name:</th>
        <th scope="col">Number:</th>
        <th scope="col">Actions:</th>
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <th scope="row"><%= contact.last_name %></th>
          <td><%= contact.first_name %></td>
          <td><%= contact.number %></td>
          <td><%= link_to 'View', contact_path(contact), 
                                    class: "btn btn-outline-success btn-sm" %>
              <%= link_to 'Edit', edit_contact_path(contact), 
                                    class: "btn btn-outline-warning btn-sm" %>
              <%= link_to 'Delete', contact_path(contact),
                                    class: "btn btn-outline-danger btn-sm", method: :delete, 
                                    data: {confirm: "Do you wish to delete #{contact.full_name}?"}%></td>
        </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/contacts/new.html.erb
<div class="container contact-area">
  <div class="justify-content-center">
    <%= render 'form' %>
  </div>
</div>

app/views/contacts/show.html.erb
<h1 class="text-center mt-4">Contact Card</h1>

<div class="container">
  <div class="row justify-content-center">
    <%= render 'contact' %>
  </div>
</div>

app/views/layouts/_messages.html.erb
  <% flash.each do |name, msg| %>
    <% if flash.alert%>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <% else %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
    <% end %>
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">Contacts 4 All</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit My Info', edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Contacts
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'New Contact', new_contact_path, class: "dropdown-item" %>
            <a class="dropdown-item" href="#">Another Action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to 'Logout', destroy_user_session_path, class: "nav-link", method: :delete %>
          <% else %>
            <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
          <% end %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contact Registry</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %> 
    <div class="container">
      <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>